### ISSUE TITLE
Performance estimations?

### ISSUE THREAD

**Issue by pavel-odintsov** [intersvyaz/zerod#1]
Hello!

Do you have any docs/performance tests?

**Comment by gureedo** [comment]
Nope, sorry.

**Comment by pavel-odintsov** [comment]
Oh, sorry. But it's very interesting project for me and I want to use it for my network platform.

**Comment by pavel-odintsov** [comment]
Where do you use it? Could it handle 100-1000 mbps of traffic?

**Comment by gureedo** [comment]
We use it as BBRAS. You can read more here http://en.wikipedia.org/wiki/Broadband_remote_access_server
It can handle up to 15Gbps and maybe more.
